from app.schemas.asignacion import AsignacionCreate, AsignacionRead
from app.schemas.asignatura import AsignaturaCreate, AsignaturaRead, AsignaturaUpdate
from app.schemas.asistencia import (
    AsistenciaBulkCreate,
    AsistenciaCreate,
    AsistenciaRead,
    AsistenciaResumenRead,
    AsistenciaUpdate,
)
from app.schemas.calendario import (
    CalendarioItem,
    CalendarioMesRead,
    CursoCreate,
    CursoRead,
    CursoUpdate,
    EventoAcademicoCreate,
    EventoAcademicoRead,
    EventoAcademicoUpdate,
    HorarioClaseCreate,
    HorarioClaseRead,
    HorarioClaseUpdate,
)
from app.schemas.dashboard import DashboardResumen, EstadisticaMensual
from app.schemas.notas import (
    EstudianteCreate,
    EstudianteRead,
    EstudianteUpdate,
    EvaluacionCreate,
    EvaluacionRead,
    EvaluacionUpdate,
    NotaCreate,
    NotaRead,
    NotaResumenItem,
    NotaResumenRead,
    NotaUpdate,
    PeriodoAcademicoCreate,
    PeriodoAcademicoRead,
    PeriodoAcademicoUpdate,
)
from app.schemas.profesor import ProfesorCreate, ProfesorRead, ProfesorUpdate

__all__ = [
    "AsignacionCreate",
    "AsignacionRead",
    "AsistenciaBulkCreate",
    "AsistenciaCreate",
    "AsistenciaRead",
    "AsistenciaResumenRead",
    "AsistenciaUpdate",
    "AsignaturaCreate",
    "AsignaturaRead",
    "AsignaturaUpdate",
    "CalendarioItem",
    "CalendarioMesRead",
    "CursoCreate",
    "CursoRead",
    "CursoUpdate",
    "DashboardResumen",
    "EstudianteCreate",
    "EstudianteRead",
    "EstudianteUpdate",
    "EstadisticaMensual",
    "EvaluacionCreate",
    "EvaluacionRead",
    "EvaluacionUpdate",
    "EventoAcademicoCreate",
    "EventoAcademicoRead",
    "EventoAcademicoUpdate",
    "HorarioClaseCreate",
    "HorarioClaseRead",
    "HorarioClaseUpdate",
    "NotaCreate",
    "NotaRead",
    "NotaResumenItem",
    "NotaResumenRead",
    "NotaUpdate",
    "PeriodoAcademicoCreate",
    "PeriodoAcademicoRead",
    "PeriodoAcademicoUpdate",
    "ProfesorCreate",
    "ProfesorRead",
    "ProfesorUpdate",
]
